defmodule DbserviceWeb.SwaggerSchema.Session do
  use PhoenixSwagger

  def session do
    %{
      Session:
        swagger_schema do
          title("Session")
          description("A session in the application")

          properties do
            name(:string, "First name")
            platform(:string, "Platform where session being hosted")
            platform_link(:string, "Link for the platform")
            portal_link(:text, "Link generated by the portal")
            start_time(:timestamp, "Session start time")
            end_time(:timestamp, "Session finish time")
            repeat_type(:string, "Repeat type for the session")
            repeat_till_date(:timestamp, "Date till ")
            meta_data(:map, "Additional meta data for the session")
            owner_id(:integer, "User ID for the session owner")
            created_by_id(:integer, "User ID for the session creator")
            is_active(:boolean, "Tells whether session is active or not")
            uuid(:string, "Uuid for the session")
          end

          example(%{
            name: "Kendriya Vidyalaya - Weekly Maths class 7",
            platform: "meet",
            platform_link: "https://meet.google.com/asl-skas-qwe",
            portal_link: "https://links.af.org/kv-wmc7",
            start_time: "2022-02-02T11:00:00Z",
            end_time: "2022-02-02T11:30:00Z",
            repeat_type: "weekly",
            repeat_till_date: "2022-12-31T11:59:59Z",
            meta_data: %{
              "substitute-teacher-name" => "Ms. Poonam"
            },
            owner_id: 2,
            created_by_id: 1,
            is_active: true,
            uuid: "uiqweopasdflkasdfj"
          })
        end,
    }
  end

  def sessions do
    %{
      Sessions:
        swagger_schema do
          title("Sessions")
          description("All the sessions")
          type(:array)
          items(Schema.ref(:Session))
        end,
    }
  end
end
